#include "../external/unit_tests.hpp"
#include "test_block.hpp"
#include "test_user.hpp"
#include "test_executor.hpp"
#include "test_crypto.hpp"
#include "test_transaction.hpp"
#include "test_request_manager.hpp"
#include "test_helpers.hpp"
#include "test_blockchain.hpp"
#include "test_merkle_tree.hpp"
TEST_MAIN();